---
name: Deploy RHCC containers to staging

on:
  workflow_dispatch:
    inputs:
      image:
        description: The full registry name and tag of the image to publish in RHCC.
        type: string
        required: true
        default: ghcr.io/calyptia/fluent-bit:ubi9
      rhcc-tag:
        description: The tag to use to publish this image under in RHCC.
        type: string
        required: true

jobs:
  publish-image:
    name: Publish the supplied image
    runs-on: ubuntu-latest
    permissions:
      packages: read
    env:
      OUTPUT_CONTAINER: scan.connect.redhat.com/ospid-61ba2990f5e42886275af1cb/ignored:${{ github.event.inputs.rhcc-tag }}
    steps:
      - name: Scan image
        run: |
          podman login -u unused --authfile ./temp-authfile.json scan.connect.redhat.com
          podman pull ${{ github.event.inputs.image }}
          podman tag ${{ github.event.inputs.image }} $OUTPUT_CONTAINER
          podman push $OUTPUT_CONTAINER
        shell: bash

      - name: Preflight checks
        run: |
          wget https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/download/1.3.1/preflight-linux-amd64
          chmod +x ./preflight-linux-amd64
          ./preflight-linux-amd64 check container $OUTPUT_CONTAINER \
            --pyxis-api-token='${{ secrets.PYXIS_API_KEY }}' \
            --certification-project-id=61ba2990f5e42886275af1cb \
            --docker-config=--authfile ./temp-authfile.json --submit